name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x, 18.x, 20.x ]
        antd-version: [ 424, 500, 510, 520, 530, 540, 550, 560, 570, 580, 590, 5100, 5110 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm install

      - name: Run Tox Jest
        run: tox -e antd_v${{ matrix.antd-version }}_jest

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        antd-version: [ 424, 500, 510, 520, 530, 540, 550, 560, 570, 580, 590, 5100, 5110 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install Tox
        run: |
          pip install --upgrade pip
          pip install tox tox-gh-actions

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/

      - name: Build and Package
        run: |
          npm install
          npm run build
          npm pack

      - name: Run Tox
        run: tox -e antd_v${{ matrix.antd-version }}
